-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,sum(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount >= (SELECT AVG(purchase_amount) AS average_purchase_amount
                       FROM customer);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased,ROUND(CAST(AVG(review_rating) AS numeric),2)
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type,ROUND(avg(purchase_amount),2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN('Standard','Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,COUNT(customer_id),ROUND(AVG(purchase_amount),2) AS average_spend,
ROUND(sum(purchase_amount),2) AS revenue
FROM customer
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT  item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/count(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased 
ORDER BY discount_rate DESC 
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type AS(
SELECT customer_id,previous_purchases,
CASE
    WHEN previous_purchases BETWEEN 0 AND 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
FROM customer
)
SELECT customer_segment,count(*) AS customer_count
FROM customer_type
GROUP BY customer_segment;
	

-- Q8. What are the top 3 most purchased products within each category?
WITH top3 AS(
SELECT category,item_purchased,count(item_purchased),
ROW_NUMBER() OVER (PARTITION BY category ORDER BY count(item_purchased) DESC) AS item_rank
FROM customer
GROUP BY category,item_purchased
)
SELECT * FROM top3
WHERE item_rank <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,count(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?
SELECT age_group,sum(purchase_amount)
FROM customer
GROUP BY age_group;

